// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEY85YgG8UKPDuvvuC00_74GgHXtVsAMA',
    appId: '1:862664113911:web:3839b530a53fb9fec19df2',
    messagingSenderId: '862664113911',
    projectId: 'deychat1-69f70',
    authDomain: 'deychat1-69f70.firebaseapp.com',
    storageBucket: 'deychat1-69f70.appspot.com',
    measurementId: 'G-HV6DBEJC2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTz1P6SI2q3MFBODoGTyHD3dAbMU-WUZg',
    appId: '1:862664113911:android:e14dc06ae5ad66a8c19df2',
    messagingSenderId: '862664113911',
    projectId: 'deychat1-69f70',
    storageBucket: 'deychat1-69f70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzgyYGZHtFbYNs8stww8jbeLi-roWwyu8',
    appId: '1:862664113911:ios:de1908f6afe4d899c19df2',
    messagingSenderId: '862664113911',
    projectId: 'deychat1-69f70',
    storageBucket: 'deychat1-69f70.appspot.com',
    iosBundleId: 'com.example.deychat1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzgyYGZHtFbYNs8stww8jbeLi-roWwyu8',
    appId: '1:862664113911:ios:de1908f6afe4d899c19df2',
    messagingSenderId: '862664113911',
    projectId: 'deychat1-69f70',
    storageBucket: 'deychat1-69f70.appspot.com',
    iosBundleId: 'com.example.deychat1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEY85YgG8UKPDuvvuC00_74GgHXtVsAMA',
    appId: '1:862664113911:web:c5d542b4916f825bc19df2',
    messagingSenderId: '862664113911',
    projectId: 'deychat1-69f70',
    authDomain: 'deychat1-69f70.firebaseapp.com',
    storageBucket: 'deychat1-69f70.appspot.com',
    measurementId: 'G-Z0WGLNYP9B',
  );
}
